# Prediction for k-Means Clusters

In [1]:
# importing required libraries
from sklearn.cluster import KMeans
import numpy as np

In [2]:
# creating sample dataset
X = np.array([[1, 2], [1, 4], [1, 0],[4, 2], [4, 4], [4, 0],[3, 2],[4, 6],[3, 6],[5, 8],[6, 9]])

In [3]:
# intializing Kmeans object with hyperparameters and fitting the Kmeans model on dataset
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [4]:
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1])

In [5]:
# predicting on new data points
kmeans.predict([[0, 0], [9, 3]])

array([0, 1])

In [6]:
# fetching clusters center
kmeans.cluster_centers_

array([[2.57142857, 2.        ],
       [4.5       , 7.25      ]])

# References

Kmeans - https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html